use_frameworks!

target 'Sharaku_Example' do
  pod 'Sharaku', :path => '../'

  target 'Sharaku_Tests' do
    inherit! :search_paths
    post_install do |installer|
        installer.generated_projects.each do |project|
              project.targets.each do |target|
                  target.build_configurations.each do |config|
                      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
                   end
              end
       end
    end
    
  end
end
